---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gp-clusterrole
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gp-serviceaccount
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gp-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gp-clusterrole
subjects:
  - kind: ServiceAccount
  name: gp-serviceacount
  namespace: default
